const parts=location.pathname.split('/').filter(Boolean).map(decodeURIComponent),slug=parts[0]||'',isEnquiry=parts[1]==='enquire';
const loading=document.querySelector('#loading'),portal=document.querySelector('#portal'),enquiry=document.querySelector('#enquiry'),missing=document.querySelector('#missing');
let activeForm=null;
const hideLoading=()=>loading.classList.add('hidden');
function unavailable(){hideLoading();missing.classList.remove('hidden')}
async function json(path,options={}){const response=await fetch(path,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{})}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail||'Something went wrong. Please try again.');return body}
async function showPortal(){const business=await json(`/api/public/business/${encodeURIComponent(slug)}`);document.documentElement.style.setProperty('--accent',business.accent_colour);document.title=`${business.display_name} · Private Client Area`;document.querySelector('#business-name').textContent=business.display_name;document.querySelector('#welcome').textContent=business.welcome_message;hideLoading();portal.classList.remove('hidden')}
function questionControl(question){const id=`question-${question.id}`,required=question.is_required?' required':'',hint=question.help_text?`<small>${escapeHtml(question.help_text)}</small>`:'',options=(question.options||[]).map(value=>`<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`).join('');let control;if(question.question_type==='long_text')control=`<textarea id="${id}" rows="5"${required}></textarea>`;else if(question.question_type==='single_choice')control=`<select id="${id}"${required}><option value="">Please choose</option>${options}</select>`;else if(question.question_type==='multiple_choice')control=`<div id="${id}" class="choice-grid">${(question.options||[]).map((value,index)=>`<label><input type="checkbox" value="${escapeHtml(value)}"> ${escapeHtml(value)}</label>`).join('')}</div>`;else if(question.question_type==='yes_no')control=`<select id="${id}"${required}><option value="">Please choose</option><option>Yes</option><option>No</option></select>`;else{const types={email:'email',phone:'tel',date:'date'},type=types[question.question_type]||'text',venue=question.question_type==='venue'?' class="venue-search" placeholder="Start typing a venue or enter it manually" autocomplete="off"':'';control=`<input id="${id}" type="${type}"${venue}${required}>`;if(question.question_type==='venue')control+=`<span class="venue-ready">⌖ Venue search ready for Google Places</span>`}return `<label class="${['long_text','multiple_choice','venue'].includes(question.question_type)?'full':''}">${escapeHtml(question.label)}${question.is_required?' *':''}${control}${hint}</label>`}
async function showEnquiry(){const form=await json(`/api/public/business/${encodeURIComponent(slug)}/enquiry-form`);activeForm=form;document.documentElement.style.setProperty('--accent',form.accent_colour);document.title=`Enquire with ${form.display_name}`;document.querySelector('#enquiry-business').textContent=form.display_name;document.querySelector('#enquiry-heading').textContent=form.heading;document.querySelector('#enquiry-introduction').textContent=form.introduction;document.querySelector('#submit-enquiry').textContent=form.submit_label;document.querySelector('#public-enquiry-form .fields').innerHTML=form.questions.map(questionControl).join('')+'<label class="honey" aria-hidden="true">Website<input id="website" tabindex="-1" autocomplete="off"></label>';hideLoading();enquiry.classList.remove('hidden')}
function escapeHtml(value=''){const d=document.createElement('div');d.textContent=value;return d.innerHTML}const money=p=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(p/100);
document.querySelector('#public-enquiry-form').addEventListener('submit',async event=>{event.preventDefault();const button=document.querySelector('#submit-enquiry');button.disabled=true;button.textContent='Sending safely…';const data={first_name:'',partner_name:'',email:'',phone:'',event_date:null,venue:'',package_interest:'',message:'',website:document.querySelector('#website')?.value||'',answers:{}};for(const question of activeForm.questions){const element=document.querySelector(`#question-${question.id}`);let value='';if(question.question_type==='multiple_choice')value=[...element.querySelectorAll('input:checked')].map(item=>item.value).join('|');else value=element.value;if(question.system_key)data[question.system_key]=value||(question.system_key==='event_date'?null:'');else data.answers[question.id]=value}try{const result=await json(`/api/public/business/${encodeURIComponent(slug)}/enquiries`,{method:'POST',body:JSON.stringify(data)});event.target.classList.add('hidden');const success=document.querySelector('#enquiry-success');success.querySelector('p').textContent=result.message;success.classList.remove('hidden')}catch(error){document.querySelector('#enquiry-error').textContent=error.message;button.disabled=false;button.textContent=activeForm.submit_label}});
async function start(){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))return unavailable();try{await(isEnquiry?showEnquiry():showPortal())}catch{return unavailable()}}start();
