const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const state={view:"overview",summary:null,tenants:[],audit:[],search:"",me:null};
let modalClosable=true;

function esc(value=""){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function attr(value=""){return esc(value)}
function cookie(name){return document.cookie.split("; ").find(item=>item.startsWith(`${name}=`))?.split("=").slice(1).join("=")||""}
async function api(path,options={}){const headers={...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(options.headers||{})};const csrf=cookie("ivory_booking_csrf");if(csrf&&!['GET','HEAD'].includes((options.method||"GET").toUpperCase()))headers["X-CSRF-Token"]=decodeURIComponent(csrf);const response=await fetch(path,{credentials:"same-origin",...options,headers});if(response.status===401&&path!=="/api/auth/login"){showLogin("Your secure session has ended. Please sign in again.");throw new Error("Please sign in again")};const data=await response.json().catch(()=>({}));if(!response.ok&&response.status!==202)throw new Error(Array.isArray(data.detail)?data.detail.map(item=>item.msg).join(", "):data.detail||"Something went wrong");return {data,status:response.status}}
function fmtDate(value){if(!value)return "—";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value))}
function fmtDateTime(value){if(!value)return "—";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function initials(name){return String(name||"ID").split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase()}
function toast(message,type=""){const el=$("#toast");el.textContent=message;el.className=`toast ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add("hidden"),3800)}
function greeting(){const hour=Number(new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",hour:"2-digit",hourCycle:"h23"}).format(new Date()));return hour<12?"Good morning":hour<18?"Good afternoon":"Good evening"}

function showLogin(message=""){$("#app-view").classList.add("hidden");$("#login-view").classList.remove("hidden");$("#login-error").textContent=message}
function showApp(){$("#login-view").classList.add("hidden");$("#app-view").classList.remove("hidden");$("#page-title").textContent=`${greeting()}, Mark`;$("#today").textContent=new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}
function openMenu(open){$("#sidebar").classList.toggle("open",open);$("#scrim").classList.toggle("hidden",!open)}

async function init(){bind();try{const result=await api("/api/auth/me");state.me=result.data;if(!state.me.is_platform_admin)throw new Error("This account belongs in Studio");if(!state.me.two_factor_enabled){showApp();await openTwoFactorSetup();return}if(state.me.assurance!=="mfa"){showLogin("Enter your authenticator code to continue.");$("#code-field").classList.remove("hidden");return}showApp();await refresh()}catch(error){if(!$("#app-view").classList.contains("hidden"))return;showLogin(error.message==="This account belongs in Studio"?error.message:"")}}

function bind(){$("#login-form").onsubmit=login;$("#logout").onclick=logout;$("#menu").onclick=()=>openMenu(true);$("#scrim").onclick=()=>openMenu(false);$("#add-business").onclick=openAddBusiness;$$('[data-view]').forEach(button=>button.onclick=()=>navigate(button.dataset.view));$("#modal-overlay").onclick=()=>{if(modalClosable)closeModal()};document.addEventListener("keydown",event=>{if(event.key==="Escape"){if(modalClosable)closeModal();openMenu(false)}})}

async function login(event){event.preventDefault();$("#login-error").textContent="";const button=event.submitter;button.disabled=true;button.textContent="Checking securely…";try{const payload={email:$("#login-email").value.trim(),password:$("#login-password").value,code:$("#login-code").value.trim()||null};const result=await api("/api/auth/login",{method:"POST",body:JSON.stringify(payload)});if(result.status===202){$("#code-field").classList.remove("hidden");$("#login-code").focus();$("#login-error").textContent="Password accepted — enter the current code from your authenticator app.";return}state.me=(await api("/api/auth/me")).data;showApp();if(result.data.requires_two_factor_setup){await openTwoFactorSetup()}else{await refresh()}}catch(error){$("#login-error").textContent=error.message}finally{button.disabled=false;button.textContent="Sign in securely"}}
async function logout(){try{await api("/api/auth/logout",{method:"POST"})}catch(_){}state.me=null;showLogin("You have signed out safely.")}

async function openTwoFactorSetup(){try{const setup=(await api("/api/auth/2fa/setup",{method:"POST"})).data;openModal(`<div class="modal-head"><div><span class="eyebrow">MANDATORY MANAGER SECURITY</span><h2>Protect your Ivory Digital Manager</h2><p>Scan this once using Google Authenticator, Microsoft Authenticator, Authy or your password manager.</p></div></div><form id="two-factor-form"><div class="form-grid"><div class="full"><img class="setup-qr" src="${attr(setup.qr_data_url)}" alt="Authenticator setup QR code"><div class="setup-key">${esc(setup.secret)}</div></div><label class="full">Enter the current 6-digit code<input id="setup-code" inputmode="numeric" autocomplete="one-time-code" maxlength="8" required></label><p id="setup-error" class="form-error full"></p></div><div class="modal-footer"><button class="button primary" type="submit">Enable two-factor security</button></div></form>`,false);$("#two-factor-form").onsubmit=async event=>{event.preventDefault();try{const enabled=(await api("/api/auth/2fa/enable",{method:"POST",body:JSON.stringify({code:$("#setup-code").value.trim()})})).data;$("#modal-content").innerHTML=`<div class="modal-head"><div><span class="eyebrow">KEEP THESE SOMEWHERE SAFE</span><h2>Your recovery codes</h2><p>Each code works once if you lose access to your authenticator. They will not be shown again.</p></div></div><div class="form-grid"><div class="recovery-codes full">${enabled.recovery_codes.map(code=>`<span>${esc(code)}</span>`).join("")}</div><p class="lead full">Copy these into your password manager before continuing.</p></div><div class="modal-footer"><button id="copy-recovery" class="button secondary">Copy codes</button><button id="finish-security" class="button primary">I have saved them</button></div>`;$("#copy-recovery").onclick=async()=>{await navigator.clipboard.writeText(enabled.recovery_codes.join("\n"));toast("Recovery codes copied")};$("#finish-security").onclick=async()=>{modalClosable=true;closeModal();state.me=(await api("/api/auth/me")).data;await refresh()}}catch(error){$("#setup-error").textContent=error.message}}}catch(error){showLogin(error.message)}}

async function refresh(){const [summary,tenants]=await Promise.all([api("/api/manager/summary"),api("/api/manager/tenants")]);state.summary=summary.data;state.tenants=tenants.data;if(state.view==="activity")state.audit=(await api("/api/manager/audit")).data;render()}
function navigate(view){state.view=view;openMenu(false);$$('[data-view]').forEach(button=>button.classList.toggle("active",button.dataset.view===view));if(view==="activity"){api("/api/manager/audit").then(result=>{state.audit=result.data;render()})}else render()}

function render(){const headings={overview:["IVORY DIGITAL",`${greeting()}, Mark`,"A clear view of every business using your platform."],businesses:["PHOTOGRAPHER BUSINESSES","Photographers","Trials, invitations and account health in one calm workspace."],activity:["SECURITY & ACCOUNTABILITY","Security and activity","Every important platform action is retained privately."]};const [kicker,title,subtitle]=headings[state.view];$("#page-kicker").textContent=kicker;$("#page-title").textContent=title;$("#page-subtitle").textContent=subtitle;if(state.view==="overview")renderOverview();else if(state.view==="businesses")renderBusinesses();else renderActivity()}
function metric(label,value,detail,icon){return `<article class="metric-card"><span>${esc(label)}<i>${icon}</i></span><strong>${esc(value)}</strong><small>${esc(detail)}</small></article>`}
function tenantRow(row){return `<div class="business-row"><span class="business-avatar">${esc(initials(row.display_name))}</span><span><strong>${esc(row.display_name)}</strong><small>${esc(row.owner_email)} · /${esc(row.slug)}</small></span><span class="status-pill ${attr(row.status)}">${esc(row.status)}</span><time>Trial ends ${esc(fmtDate(row.trial_ends_at))}</time><div class="row-actions"><button class="mini-button" data-open-tenant="${attr(row.id)}">Open</button></div></div>`}
function wireTenantRows(){$$('[data-open-tenant]').forEach(button=>button.onclick=()=>openTenant(button.dataset.openTenant))}
function renderOverview(){const s=state.summary||{},recent=state.tenants.slice(0,6);$("#content").innerHTML=`<section class="metric-grid">${metric("All businesses",s.businesses||0,"Across trials and subscriptions","◇")}${metric("30-day trials",s.trial||0,"Photographers exploring Studio","◷")}${metric("Active",s.active||0,"Live business accounts","✓")}${metric("Invitations waiting",s.pending_invitations||0,"Secure setup links not yet used","↗")}</section><section class="manager-grid"><article class="panel"><header class="panel-head"><div><h2>Recently added photographers</h2><p>Open a business to review account health safely.</p></div><button data-jump="businesses">View everyone</button></header>${recent.length?recent.map(tenantRow).join(""):`<div class="empty-state"><strong>No photographer businesses yet</strong><p>Your first fictional test studio can be added when you are ready.</p></div>`}</article><aside class="panel"><header class="panel-head"><div><h2>Foundation checks</h2><p>Phase One protection</p></div></header><div class="checklist"><div><i>✓</i><span><strong>Manager two-factor security</strong><small>Required before platform controls open.</small></span></div><div><i>✓</i><span><strong>Photographer separation</strong><small>Every client and booking belongs to one business.</small></span></div><div><i>✓</i><span><strong>Private audit history</strong><small>Support and account changes are recorded.</small></span></div><div><i>✓</i><span><strong>Automations begin paused</strong><small>Nothing contacts couples during setup.</small></span></div></div></aside></section>`;wireTenantRows();$("[data-jump='businesses']")?.addEventListener("click",()=>navigate("businesses"))}
function renderBusinesses(){const matches=state.tenants.filter(row=>`${row.display_name} ${row.owner_email} ${row.slug}`.toLowerCase().includes(state.search));$("#content").innerHTML=`<div class="toolbar"><label class="search-box">⌕<input id="business-search" placeholder="Search business, owner or client address" value="${attr(state.search)}"></label><button class="button primary" id="add-business-inline">＋ Add photographer</button></div><section class="panel table-panel"><div class="business-table"><div class="business-row"><span></span><span>Business</span><span>Status</span><span>Trial</span><span>Actions</span></div>${matches.map(tenantRow).join("")||`<div class="empty-state"><strong>No matching businesses</strong><p>Try a different name or email address.</p></div>`}</div></section>`;$("#business-search").oninput=event=>{state.search=event.target.value.toLowerCase();renderBusinesses()};$("#add-business-inline").onclick=openAddBusiness;wireTenantRows()}
function renderActivity(){const rows=state.audit||[];$("#content").innerHTML=`<section class="panel"><header class="panel-head"><div><h2>Private audit history</h2><p>The newest platform actions appear first.</p></div></header>${rows.length?rows.map(row=>`<div class="audit-row"><span><strong>${esc(row.action.replaceAll("_"," "))}</strong><small>${esc(row.subject_type)}${row.subject_id?` · ${esc(row.subject_id)}`:""}</small></span><small>${row.tenant_id?`Business ${esc(row.tenant_id)}`:"Platform"}</small><time>${esc(fmtDateTime(row.created_at))}</time></div>`).join(""):`<div class="empty-state"><strong>No activity yet</strong></div>`}</section>`}

function openModal(html,closable=true){modalClosable=closable;$("#modal-content").innerHTML=html;$("#modal").classList.remove("hidden");$("#modal-overlay").classList.remove("hidden");if(closable){$(".modal-close")?.addEventListener("click",closeModal)}}
function closeModal(){if(!modalClosable)return;$("#modal").classList.add("hidden");$("#modal-overlay").classList.add("hidden");$("#modal-content").innerHTML=""}
function openAddBusiness(){openModal(`<div class="modal-head"><div><span class="eyebrow">NEW PHOTOGRAPHER</span><h2>Create a 30-day trial</h2><p>This creates an empty, isolated business and one secure owner invitation. No couple is contacted.</p></div><button class="modal-close" type="button">×</button></div><form id="business-form"><div class="form-grid"><label class="full">Photography business name<input id="business-name" placeholder="Example Wedding Studio" required></label><label>Owner's name<input id="owner-name" placeholder="Alex Morgan" required></label><label>Owner's email<input id="owner-email" type="email" placeholder="alex@example.co.uk" required></label><label class="full">Private client address<input id="business-slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="example-wedding-studio" required><small>client.ivorydigital.uk/<b id="slug-preview">example-wedding-studio</b></small></label><input id="timezone" type="hidden" value="Europe/London"><p id="business-error" class="form-error full"></p></div><div class="modal-footer"><button class="button secondary modal-close" type="button">Cancel</button><button class="button primary" type="submit">Create secure trial</button></div></form>`);const name=$("#business-name"),slug=$("#business-slug");let manual=false;slug.oninput=()=>{manual=true;$("#slug-preview").textContent=slug.value||"business-name"};name.oninput=()=>{if(!manual){slug.value=name.value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80);$("#slug-preview").textContent=slug.value||"business-name"}};$$('.modal-close').forEach(button=>button.onclick=closeModal);$("#business-form").onsubmit=createBusiness}
async function createBusiness(event){event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent="Creating safely…";try{const result=(await api("/api/manager/tenants",{method:"POST",body:JSON.stringify({display_name:$("#business-name").value.trim(),slug:$("#business-slug").value.trim(),owner_name:$("#owner-name").value.trim(),owner_email:$("#owner-email").value.trim(),timezone:$("#timezone").value})})).data;await refresh();showInvitation(result)}catch(error){$("#business-error").textContent=error.message;button.disabled=false;button.textContent="Create secure trial"}}
function showInvitation(tenant){const url=tenant.invitation.setup_url;$("#modal-content").innerHTML=`<div class="modal-head"><div><span class="eyebrow">TRIAL CREATED SAFELY</span><h2>${esc(tenant.display_name)} is ready</h2><p>The business is empty, automatic messages are paused and its data area is isolated.</p></div><button class="modal-close">×</button></div><div class="form-grid"><div class="invitation-box full"><strong>Private owner setup link</strong><small>Expires ${esc(fmtDateTime(tenant.invitation.expires_at))}. Send this only to ${esc(tenant.owner_email)}.</small><input id="invitation-url" value="${attr(url)}" readonly><button id="copy-invitation" class="button primary wide">Copy secure invitation</button></div><p class="lead full">They will create their own password. Ivory Digital never sends or stores a shared temporary password.</p></div><div class="modal-footer"><button class="button secondary modal-close">Done</button></div>`;$$('.modal-close').forEach(button=>button.onclick=closeModal);$("#copy-invitation").onclick=async()=>{await navigator.clipboard.writeText(url);toast("Secure invitation copied")}}
async function openTenant(id){try{const support=(await api(`/api/manager/tenants/${id}/support`)).data,t=support.tenant;openModal(`<div class="modal-head"><div><span class="eyebrow">SAFE SUPPORT VIEW</span><h2>${esc(t.display_name)}</h2><p>You are viewing health and counts only. No couple details have been opened.</p></div><button class="modal-close">×</button></div><div class="form-grid"><div class="full invitation-box"><strong>${esc(t.client_url)}</strong><small>${esc(t.owner_email)} · ${esc(t.status.toUpperCase())} · trial ends ${esc(fmtDate(t.trial_ends_at))}</small></div><label>Clients<input value="${support.client_count}" readonly></label><label>Bookings<input value="${support.booking_count}" readonly></label><label class="full">Automatic messages<select id="tenant-automations"><option value="true" ${t.automations_paused?"selected":""}>Paused — safest during setup</option><option value="false" ${t.automations_paused?"":"selected"}>Allowed by photographer workflows</option></select></label><label class="full">Reason for this change<input id="automation-reason" value="Platform support review" maxlength="500"></label></div><div class="modal-footer"><button id="resend-invite" class="button secondary">New invitation</button><button id="save-automations" class="button primary">Save safety setting</button></div>`);$(".modal-close").onclick=closeModal;$("#save-automations").onclick=async()=>{const paused=$("#tenant-automations").value==="true";await api(`/api/manager/tenants/${id}/automations`,{method:"PATCH",body:JSON.stringify({paused,reason:$("#automation-reason").value.trim()})});toast(paused?"Automatic messages paused":"Automatic messages released to workflows");closeModal();await refresh()};$("#resend-invite").onclick=async()=>{const invite=(await api(`/api/manager/tenants/${id}/invite`,{method:"POST"})).data;await navigator.clipboard.writeText(invite.setup_url);toast("New invitation copied; the previous link is cancelled")}}catch(error){toast(error.message,"error")}}

init();
