const openTenantBefore59=openTenant;
openTenant=async function(id){await openTenantBefore59(id);const footer=$('#modal-content .modal-footer');if(footer){const b=document.createElement('button');b.className='button secondary';b.textContent='Businesses on this seat';b.onclick=()=>openSeat(id);footer.prepend(b)}};
const openBillingBefore59=openBilling;
openBilling=async function(id){await openBillingBefore59(id);const b=document.createElement('button');b.className='button secondary';b.textContent='Manage second business';b.onclick=()=>openSeat(id);$('#modal-content')?.append(b)};
async function openSeat(id){
 try{
  const data=(await api(`/api/manager/tenants/${id}/businesses`)).data;
  const child=data.businesses.find(b=>b.second);
  openModal(`<div class="modal-head"><div><span class="eyebrow">ONE SEAT · UP TO TWO BUSINESSES</span><h2>Business access</h2><p>Each business has its own clients, branding, bank accounts and Stripe account.</p></div><button class="modal-close">×</button></div>${data.businesses.map(b=>`<p><strong>${esc(b.name)}</strong> — ${b.second?'Second':'Primary'} business · ${esc(b.status)} · ${money(b.subscription.price_pence)} / ${esc(b.subscription.billing_cycle)}</p>`).join('')}<form id="seat-form" class="form-grid">${child?'':`<label class="full">Second business name<input id="seat-name" required minlength="2" maxlength="160"></label><label class="full">Client address<input id="seat-slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" minlength="2" maxlength="80" placeholder="second-business"></label>`}<label class="full">Access<select id="seat-access"><option value="free" ${!child?.subscription.price_pence?'selected':''}>Grant free access</option><option value="paid" ${child?.subscription.price_pence?'selected':''}>Charge a subscription</option></select></label><label>Charge (£)<input id="seat-price" type="number" min="0.30" max="100000" step="0.01" value="${child?child.subscription.price_pence/100:''}"></label><label>Billing cycle<select id="seat-cycle"><option value="monthly">Monthly</option><option value="yearly" ${child?.subscription.billing_cycle==='yearly'?'selected':''}>Yearly</option></select></label><p class="full">A paid second business opens after a verified subscription payment or after you record a bank payment and grant access. No charge is taken by saving this form. Before changing a running Stripe subscription, cancel it in Stripe. Existing records are retained.</p><p id="seat-error" class="error full" role="alert"></p><button type="submit" class="button primary full">${child?'Save second business access':'Create second business'}</button></form>`);
  const choice=$('#seat-access'),price=$('#seat-price');const sync=()=>{price.disabled=choice.value==='free';price.required=!price.disabled};choice.onchange=sync;sync();
  $('#seat-form').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const body={price_pence:choice.value==='free'?0:Math.round(Number(price.value)*100),billing_cycle:$('#seat-cycle').value};if(child){body.complimentary=choice.value==='free';await api(`/api/manager/tenants/${child.id}/business-access`,{method:'PUT',body:JSON.stringify(body)})}else{body.display_name=$('#seat-name').value;body.slug=$('#seat-slug').value;await api(`/api/manager/tenants/${data.primary_id}/businesses`,{method:'POST',body:JSON.stringify(body)})}await openSeat(data.primary_id)}catch(err){$('#seat-error').textContent=err.message;button.disabled=false}};
 }catch(err){toast(err.message,true)}
}
