"""Additive accounting help; preserves administrator edits to existing articles."""
PHASE510_HELP_ARTICLES = (
    {'slug':'phase510-connect-accounting','title':'How do I connect QuickBooks or Xero?', 'category':'Payments',
     'contexts':['home','brand','payments'], 'keywords':['accounting','QuickBooks','Xero','connect','tax'],
     'summary':'The business owner opens Accounting at the top of Studio.',
     'body':'First select the correct Current business. Open Accounting and choose QuickBooks Online or Xero. If it says Awaiting Ivory Digital setup, the platform credentials have not been enabled yet. Sign in directly with your provider, authorise access and select this business’s UK accounting company. Each business has a separate connection; one accounting company cannot be shared between businesses. Choose the sales account or service item, sales tax code, bank transfer account and Stripe clearing account. Prices are treated as VAT-inclusive with one tax code for the whole invoice: confirm these choices with your accountant. Mixed-tax invoices need manual accounting. Save, then test one invoice using Sync invoice & payments. Sage Accounting is planned for a later release.',
     'action_label':'Open Home','action_route':'home','tour_key':'home','sort_order':3},
    {'slug':'phase510-accounting-sync','title':'Which invoices and payments are sent to my accounts?', 'category':'Payments',
     'contexts':['home','weddings','payments'], 'keywords':['accounting','automatic','sync','invoice','bank','Stripe'],
     'summary':'Automatic syncing is optional; older invoices require a manual choice.',
     'body':'Accounting sends invoices and recorded bank transfer or Stripe payments out to your accounts. Check that an invoice has not already been entered in your accounting software before choosing Sync. The provider gives it its own invoice number; the Ivory invoice number and item breakdown appear in its description. One gross service line preserves the full invoice total including discounts. If you enable automatic syncing, invoices created since the first time you saved accounting settings are eligible, plus later payments on previously exported invoices. Accounting entries and payments are not imported back into Ivory. No invoice emails are sent by the integration. Stripe receipts are gross; reconcile fees and payouts separately. Couples still use the same card and bank transfer options and never see these private accounting controls.',
     'action_label':'Open Home','action_route':'home','tour_key':'home','sort_order':4},
    {'slug':'phase510-accounting-review','title':'What does Needs attention mean in Accounting?', 'category':'Payments',
     'contexts':['home','weddings','payments'], 'keywords':['accounting','error','refund','void','duplicate','disconnect'],
     'summary':'Unconfirmed exports stop for review to avoid duplicate entries.',
     'body':'Open Accounting and check Needs attention. For a rejected request, correct the settings and retry from the invoice. If the provider did not confirm a request, inspect its records first. If you find the matching record, choose Match existing accounting record and enter its provider record ID; Ivory checks it before linking. If you cannot find it, contact Ivory support instead of creating repeated exports. Refunds, void invoices and changes after export require review and any adjustments in your accounting software; Ivory does not automatically create credit notes or overwrite accounting records. Disconnect removes the saved tokens and stops sync while retaining the export history. You can also revoke access in the provider. Reconnect the original provider and company to preserve that history.',
     'action_label':'Open Home','action_route':'home','tour_key':'home','sort_order':5},
)
