const $ = (q) => document.querySelector(q);
const csrf = () => document.cookie.split('; ').find(v => v.startsWith('ivory_booking_csrf='))?.split('=')[1] || '';
let dashboard;
let packages=[], addOns=[], workflows=[];
const triggers={enquiry_received:'Enquiry received',quote_sent:'Quote sent',quote_accepted:'Quote accepted',booking_fee_paid:'Booking fee paid',contract_signed:'Contract signed',questionnaire_submitted:'Questionnaire submitted',balance_due:'Balance due',balance_paid:'Balance paid',wedding_date:'Wedding date',wedding_completed:'Wedding completed'};

async function api(path, options = {}) {
  const headers = {...(options.body ? {'Content-Type':'application/json'} : {}), ...(options.headers || {})};
  if (!['GET','HEAD'].includes((options.method || 'GET').toUpperCase())) headers['X-CSRF-Token'] = csrf();
  const response = await fetch(path, {...options, headers, credentials:'same-origin'});
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.detail || 'Something went wrong. Please try again.');
  return body;
}

function toast(message, bad=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',bad);el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3500)}
function initials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'}
function daysLeft(value){return Math.max(0,Math.ceil((new Date(value)-new Date())/86400000))}

async function showInvitation(token){
  try{
    const invite=await api(`/api/invitations/${encodeURIComponent(token)}`);
    $('#auth-card').innerHTML=`<div class="eyebrow">YOU'RE INVITED</div><h1>Welcome to ${escapeHtml(invite.business_name)}</h1><p class="lead">Create your private login and your 30-day trial will be ready to explore.</p><form id="invite-form"><label>Your name<input id="invite-name" autocomplete="name" required minlength="2"></label><label>Email address<input value="${escapeHtml(invite.email)}" disabled></label><label>Create a password<input id="invite-password" type="password" autocomplete="new-password" required minlength="14"><small>At least 14 characters, including upper and lowercase letters, a number and a symbol.</small></label><p id="auth-error" class="error"></p><button class="button primary wide" type="submit">Create my studio</button></form><p class="secure-note">This personal invitation expires automatically and can only be used once.</p>`;
    $('#invite-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='Preparing your studio…';try{await api(`/api/invitations/${encodeURIComponent(token)}/accept`,{method:'POST',body:JSON.stringify({full_name:$('#invite-name').value,password:$('#invite-password').value})});history.replaceState({},'',location.pathname);await openStudio()}catch(err){$('#auth-error').textContent=err.message;button.disabled=false;button.textContent='Create my studio'}});
  }catch(err){$('#auth-card').innerHTML=`<div class="eyebrow">INVITATION HELP</div><h1>That link is no longer available</h1><p class="lead">${escapeHtml(err.message)}. Ask Ivory Digital for a fresh setup invitation.</p>`}
}

function escapeHtml(value=''){const d=document.createElement('div');d.textContent=value;return d.innerHTML}

function render(){
  const {user,tenant,onboarding}=dashboard;
  $('#profile-name').textContent=user.full_name;$('#profile-role').textContent=user.role;$('#initials').textContent=initials(user.full_name);
  $('#top-business').textContent=tenant.display_name;$('#greeting').textContent=`${greeting()}, ${user.full_name.split(' ')[0]}`;
  $('#today').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
  const days=daysLeft(tenant.trial_ends_at);$('#trial-days').textContent=days;$('#trial-chip').textContent=`${days} day${days===1?'':'s'} left in trial`;
  const steps=[
    ['business','Business details','Add your trading name and the essentials couples should see.','✦',true],
    ['branding','Brand and welcome','Choose your colour and write a warm client welcome.','◈',true],
    ['packages','Packages and pricing','Build the services couples can choose from.','£',true],
    ['templates','Emails and workflow','Create your own timings and message style.','✉',true],
    ['calendar','Connect your calendar','Keep every confirmed date together.','□',false],
    ['ready','Review and go live','We will check everything with you before anything sends.','✓',false]
  ];
  const complete=steps.filter(s=>onboarding[s[0]]).length;const pct=Math.round(complete/steps.length*100);
  $('#progress-bar').style.width=`${pct}%`;$('#progress-label').textContent=`${pct}% ready`;
  $('#checklist').innerHTML=steps.map(([key,title,copy,icon,available])=>`<div class="setup-item ${onboarding[key]?'done':''}"><span class="setup-icon">${onboarding[key]?'✓':icon}</span><div><strong>${title}</strong><small>${onboarding[key]?'Complete':copy}</small></div><button data-step="${key}" ${available?'':'disabled'}>${onboarding[key]?'Review':available?'Set up':'Coming soon'}</button></div>`).join('');
  document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>showSection(({business:'brand',branding:'brand',packages:'packages',templates:'workflow'})[b.dataset.step]||'home')));
  const brand=tenant.branding||{};$('#business-name').value=brand.display_name||tenant.display_name;$('#accent').value=brand.accent_colour||'#a9782e';$('#accent-text').value=brand.accent_colour||'#a9782e';$('#welcome-message').value=brand.welcome_message||'Welcome to your private booking area.';updatePreview();
}

function updatePreview(){const colour=$('#accent-text').value;$('#preview-name').textContent=$('#business-name').value||'Your business';$('#preview-message').textContent=$('#welcome-message').value||'Welcome to your private booking area.';if(/^#[0-9a-f]{6}$/i.test(colour))document.documentElement.style.setProperty('--preview',colour);$('.portal-preview button').style.background=colour}
async function showSection(name){['home','brand','packages','workflow'].forEach(x=>$(`#${x}-section`).classList.toggle('hidden',name!==x));document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===name));closeMenu();scrollTo({top:0,behavior:'smooth'});if(name==='packages')await loadPackages();if(name==='workflow')await loadWorkflow()}
function closeMenu(){$('#sidebar').classList.remove('open');$('#scrim').classList.add('hidden')}

async function openStudio(){
  try{dashboard=await api('/api/studio/dashboard');$('#auth-view').classList.add('hidden');$('#studio-view').classList.remove('hidden');render()}
  catch{$('#auth-view').classList.remove('hidden');$('#studio-view').classList.add('hidden')}
}

$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='Opening your studio…';$('#auth-error').textContent='';try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});if(result.destination!=='studio')throw new Error('Please use Ivory Digital Manager for this account.');await openStudio()}catch(err){$('#auth-error').textContent=err.message;button.disabled=false;button.textContent='Open my studio'}});
$('#brand-form').addEventListener('input',e=>{if(e.target.id==='accent')$('#accent-text').value=e.target.value;if(e.target.id==='accent-text'&&/^#[0-9a-f]{6}$/i.test(e.target.value))$('#accent').value=e.target.value;updatePreview()});
$('#brand-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='Saving…';try{await api('/api/studio/branding',{method:'PATCH',body:JSON.stringify({display_name:$('#business-name').value,accent_colour:$('#accent-text').value,welcome_message:$('#welcome-message').value})});dashboard=await api('/api/studio/dashboard');render();toast('Your business details are saved.');showSection('home')}catch(err){$('#brand-error').textContent=err.message}finally{b.disabled=false;b.textContent='Save business details'}});
$('#logout').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}finally{location.reload()}});$('#menu').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#scrim').classList.remove('hidden')});$('#scrim').addEventListener('click',closeMenu);$('#back-home').addEventListener('click',()=>showSection('home'));document.querySelectorAll('.back-home').forEach(b=>b.addEventListener('click',()=>showSection('home')));document.querySelectorAll('[data-section]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));

const money=p=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(p/100);
const pence=v=>Math.round((Number(v)||0)*100);
function empty(title,copy){return `<div class="empty"><span>✦</span><strong>${title}</strong><p>${copy}</p></div>`}
async function loadPackages(){try{[packages,addOns]=await Promise.all([api('/api/studio/packages'),api('/api/studio/add-ons')]);$('#package-list').innerHTML=packages.length?packages.map(p=>`<button class="catalogue-card" data-package="${p.id}"><span class="status ${p.is_active?'live':'off'}">${p.is_active?'Available':'Hidden'}</span><strong>${escapeHtml(p.name)}</strong><p>${escapeHtml(p.short_description||'No description yet')}</p><footer><b>${money(p.price_pence)}</b><small>${money(p.booking_fee_pence)} booking fee · balance ${p.balance_due_days} days before</small></footer></button>`).join(''):empty('Your first package starts here','Add a clear collection couples can confidently choose.');$('#addon-list').innerHTML=addOns.length?addOns.map(a=>`<button class="addon-card" data-addon="${a.id}"><div><strong>${escapeHtml(a.name)}</strong><small>${a.selection_mode==='mandatory'?'Mandatory':'Optional'} · ${a.is_active?'Available':'Hidden'}</small></div><b>${money(a.price_pence)}</b></button>`).join(''):empty('No add-ons yet','Add albums, extra hours or complimentary extras when you are ready.');document.querySelectorAll('[data-package]').forEach(b=>b.onclick=()=>openPackage(packages.find(p=>p.id===b.dataset.package)));document.querySelectorAll('[data-addon]').forEach(b=>b.onclick=()=>openAddon(addOns.find(a=>a.id===b.dataset.addon)))}catch(e){toast(e.message,true)}}
function openPackage(p){$('#package-form').reset();$('#package-id').value=p?.id||'';$('#package-dialog-title').textContent=p?'Edit package':'Add a package';$('#package-name').value=p?.name||'';$('#package-description').value=p?.short_description||'';$('#package-price').value=p?p.price_pence/100:'';$('#package-fee').value=p?p.booking_fee_pence/100:100;$('#package-balance').value=p?.balance_due_days??45;$('#package-inclusions').value=(p?.inclusions||[]).join('\n');$('#package-featured').checked=!!p?.is_featured;$('#package-active').checked=p?p.is_active:true;$('#package-error').textContent='';$('#package-dialog').showModal()}
function openAddon(a){$('#addon-form').reset();$('#addon-id').value=a?.id||'';$('#addon-dialog-title').textContent=a?'Edit add-on':'Add an extra';$('#addon-name').value=a?.name||'';$('#addon-description').value=a?.description||'';$('#addon-price').value=a?a.price_pence/100:0;$('#addon-mode').value=a?.selection_mode||'optional';$('#addon-reason').value=a?.mandatory_reason||'';$('#addon-active').checked=a?a.is_active:true;toggleReason();$('#addon-error').textContent='';$('#addon-dialog').showModal()}
$('#new-package').onclick=()=>openPackage();$('#new-addon').onclick=()=>openAddon();$('#addon-mode').onchange=toggleReason;function toggleReason(){$('#reason-wrap').classList.toggle('hidden',$('#addon-mode').value!=='mandatory')}
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#package-form').onsubmit=async e=>{e.preventDefault();const id=$('#package-id').value,data={name:$('#package-name').value,short_description:$('#package-description').value,price_pence:pence($('#package-price').value),booking_fee_pence:pence($('#package-fee').value),balance_due_days:Number($('#package-balance').value),inclusions:$('#package-inclusions').value.split('\n'),is_featured:$('#package-featured').checked,is_active:$('#package-active').checked,sort_order:packages.length};try{await api(`/api/studio/packages${id?'/'+id:''}`,{method:id?'PATCH':'POST',body:JSON.stringify(data)});$('#package-dialog').close();await loadPackages();dashboard=await api('/api/studio/dashboard');render();toast(id?'Package updated.':'Package added.')}catch(err){$('#package-error').textContent=err.message}};
$('#addon-form').onsubmit=async e=>{e.preventDefault();const id=$('#addon-id').value,data={name:$('#addon-name').value,description:$('#addon-description').value,price_pence:pence($('#addon-price').value),selection_mode:$('#addon-mode').value,mandatory_reason:$('#addon-reason').value,is_active:$('#addon-active').checked,sort_order:addOns.length};try{await api(`/api/studio/add-ons${id?'/'+id:''}`,{method:id?'PATCH':'POST',body:JSON.stringify(data)});$('#addon-dialog').close();await loadPackages();toast(id?'Add-on updated.':'Add-on added.')}catch(err){$('#addon-error').textContent=err.message}};

async function loadWorkflow(){try{workflows=await api('/api/studio/workflows');if(!workflows.length){await api('/api/studio/workflows',{method:'POST',body:JSON.stringify({name:'Main client journey',description:'Your enquiry-to-wedding workflow.',is_active:false,sort_order:0})});workflows=await api('/api/studio/workflows')}const w=workflows[0];$('#workflow-name').textContent=w.name;$('#workflow-revision').textContent=`Revision ${w.revision} · Draft`;$('#workflow-steps').innerHTML=w.steps.length?w.steps.map((s,i)=>`<button class="timeline-step" data-step-id="${s.id}"><span class="step-number">${i+1}</span><div><small>${escapeHtml(triggers[s.trigger_event])}</small><strong>${escapeHtml(s.name)}</strong><p>${s.timing_direction==='immediately'?'Immediately':`${s.offset_value} ${s.offset_unit} ${s.timing_direction}`} · ${s.action_type==='email'?'Email to couple':'Manual task'}</p></div><em>${s.is_paused?'Paused':'Ready'}</em></button>`).join(''):empty('Build your first step','Start with a manual reminder or prepare an email. Every new step is paused.');document.querySelectorAll('[data-step-id]').forEach(b=>b.onclick=()=>openStep(w.steps.find(s=>s.id===b.dataset.stepId)))}catch(e){toast(e.message,true)}}
function openStep(s){$('#step-form').reset();$('#step-id').value=s?.id||'';$('#step-dialog-title').textContent=s?'Edit workflow step':'Add a workflow step';$('#step-trigger').innerHTML=Object.entries(triggers).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('#step-name').value=s?.name||'';$('#step-trigger').value=s?.trigger_event||'enquiry_received';$('#step-direction').value=s?.timing_direction||'after';$('#step-offset').value=s?.offset_value??1;$('#step-unit').value=s?.offset_unit||'days';$('#step-action').value=s?.action_type||'manual_task';$('#step-task').value=s?.task_title||'';$('#step-subject').value=s?.subject||'';$('#step-message').value=s?.message_body||'';$('#step-paused').checked=s?s.is_paused:true;toggleStepFields();$('#step-error').textContent='';$('#step-dialog').showModal()}
function toggleStepFields(){const email=$('#step-action').value==='email',instant=$('#step-direction').value==='immediately';$('#task-wrap').classList.toggle('hidden',email);$('#subject-wrap').classList.toggle('hidden',!email);$('#message-wrap').classList.toggle('hidden',!email);$('#offset-wrap').classList.toggle('hidden',instant)}
$('#new-step').onclick=()=>openStep();$('#step-action').onchange=toggleStepFields;$('#step-direction').onchange=toggleStepFields;
$('#step-form').onsubmit=async e=>{e.preventDefault();const w=workflows[0],id=$('#step-id').value,data={name:$('#step-name').value,trigger_event:$('#step-trigger').value,timing_direction:$('#step-direction').value,offset_value:$('#step-direction').value==='immediately'?0:Number($('#step-offset').value),offset_unit:$('#step-unit').value,action_type:$('#step-action').value,subject:$('#step-subject').value,message_body:$('#step-message').value,task_title:$('#step-task').value,is_paused:$('#step-paused').checked,sort_order:w.steps.length};try{await api(`/api/studio/workflows/${w.id}/steps${id?'/'+id:''}`,{method:id?'PATCH':'POST',body:JSON.stringify(data)});$('#step-dialog').close();await loadWorkflow();dashboard=await api('/api/studio/dashboard');render();toast(id?'Workflow step updated.':'Workflow step added safely — it is paused.')}catch(err){$('#step-error').textContent=err.message}};

const invite=new URLSearchParams(location.search).get('invite');if(invite)showInvitation(invite);else openStudio();
