// Phase 5.8: tenant bank choices, saved payment instructions and safe quote review.
function studioBankChoices(){const b=dashboard?.tenant?.branding||{};if(Array.isArray(b.bank_accounts))return b.bank_accounts;return b.bank_account_name?[{id:'account1',label:'Current bank',bank_account_name:b.bank_account_name,bank_sort_code:b.bank_sort_code||'',bank_account_number:b.bank_account_number||''}]:[]}
function bankSelect(id,value,saved){const rows=studioBankChoices(),chosen=value||'';return `<label>Bank account for this quote<select id="${id}"><option value="">Original bank transfer details</option>${rows.map(r=>`<option value="${r.id}" ${chosen===r.id?'selected':''}>${escapeHtml(r.label)} · ending ${escapeHtml(r.bank_account_number.slice(-4))}</option>`).join('')}${chosen&&!rows.some(r=>r.id===chosen)?`<option value="${escapeAttr(chosen)}" selected>${escapeHtml(saved?.label||'Previously selected bank')} · saved details</option>`:''}</select><small>Existing quotes keep their saved details when the same bank remains selected. Choose a different bank to change this quote.</small></label>`}
function paymentSummary(p){if(!p)return '<p>Original bank transfer details</p>';return `<div class="bank-summary"><strong>${escapeHtml(p.label||'Bank transfer')}</strong><p>${escapeHtml(p.bank_account_name||'Account name not set')}<br>Sort code: ${escapeHtml(p.bank_sort_code||'Not set')} · Account number: ${escapeHtml(p.bank_account_number||'Not set')}</p><small>Saved with this quote or invoice. Changing Business settings will not redirect this payment.</small></div>`}
function quoteReviewSummary(j){const q=j.quote||{},custom=q.custom_items||[],extra=q.add_ons||[],required=extra.filter(a=>a.selection_mode==='mandatory'),optional=extra.filter(a=>a.selection_mode!=='mandatory');const list=(items,name)=>items.length?items.map(a=>`<li>${escapeHtml(a[name])} — ${money(a.price_pence)}${a.eligible_package_ids?.length?' (package restrictions apply)':''}</li>`).join(''):'<li>None</li>';return `<section class="quote-review-summary"><h3>Check this quote before sending</h3><p>The couple chooses one package. Totals below include compulsory items and adjustments, but exclude optional extras.</p><div class="table-wrap"><table><thead><tr><th>Package</th><th>Base price</th><th>Total with required items</th></tr></thead><tbody>${(q.packages||[]).map(p=>{const total=p.price_pence+required.filter(a=>!a.eligible_package_ids?.length||a.eligible_package_ids.includes(p.id)).reduce((s,a)=>s+a.price_pence,0)+custom.reduce((s,a)=>s+a.price_pence,0);return `<tr><td>${escapeHtml(p.name)}</td><td>${money(p.price_pence)}</td><td>${money(total)}${total<0?' — check discount':''}</td></tr>`}).join('')}</tbody></table></div><h4>Compulsory charges</h4><ul>${list(required,'name')}</ul><h4>Optional extras the couple can choose</h4><ul>${list(optional,'name')}</ul><h4>Discounts and other adjustments</h4><ul>${list(custom,'label')}</ul><h4>Bank requested for this booking</h4>${paymentSummary(q.payment_details||j.payment_details)}<p><a class="button quiet" target="_blank" rel="noopener" href="/api/studio/bookings/${encodeURIComponent(j.id)}/couple-preview">Preview as the couple ↗</a></p></section>`}
const quoteBuilder58=quoteBuilder;
quoteBuilder=function(j){return quoteBuilder58(j).replace('</article>',`<section class="quote-builder-section">${bankSelect('quote-bank-account',j.quote?.bank_account_id,j.quote?.payment_details)}${j.quote?.payment_details?paymentSummary(j.quote.payment_details):''}<p><button id="preview-couple-quote" class="button quiet" type="button">Save & preview as the couple</button></p></section></article>`)};
const couplePanel58=couplePanel;
couplePanel=function(j){return couplePanel58(j)+`<article class="panel workspace-card"><h3>Bank for this booking</h3>${paymentSummary(j.payment_details)}</article>`};
const invoicePanel58=invoicePanel;
invoicePanel=function(i){return invoicePanel58(i).replace('</article>',`<section class="quote-builder-section"><h4>Bank on this invoice</h4>${paymentSummary(i.payment_details)}</section></article>`)};
const wireClientJourneyControls58=wireClientJourneyControls;
wireClientJourneyControls=function(){wireClientJourneyControls58();$('#preview-couple-quote')?.addEventListener('click',async()=>{const opened=window.open('about:blank','_blank');if(opened)opened.opener=null;try{activeJourney=await api(`/api/studio/bookings/${activeJourney.id}/quote`,{method:'PUT',body:JSON.stringify(quoteDraftPayload())});const url=`/api/studio/bookings/${encodeURIComponent(activeJourney.id)}/couple-preview`;if(opened)opened.location.href=url;else{const d=openWorkDialog('Your saved quote is ready to preview','NO EMAIL SENT',`<a class="button primary" href="${url}" target="_blank" rel="noopener">Open couple preview</a>`,async()=>{},'Done')}await refreshActiveJourney()}catch(e){opened?.close();toast(e.message,true)}})};
const openQuoteTemplate58=openQuoteTemplate;
openQuoteTemplate=async function(row){await openQuoteTemplate58(row);const title=$('#qt-name');if(title)title.closest('label').insertAdjacentHTML('afterend',bankSelect('qt-bank-account',row?.bank_account_id))};
$('#manage-bank-accounts').onclick=async()=>{try{const result=await api('/api/studio/bank-accounts');const body=`<p>Leave your original bank transfer fields alone during the transition. Saving these choices does not change existing invoices.</p>${['account1','account2'].map((id,i)=>{const r=result.accounts.find(a=>a.id===id)||{},enabled=!!(r.bank_account_name&&r.bank_sort_code&&r.bank_account_number);return `<fieldset class="bank-editor" data-bank-slot="${id}"><legend>Account ${i+1}</legend><label class="check"><input class="bank-enabled" type="checkbox" ${enabled?'checked':''}> Available for new quotes</label><label>Private label<input class="bank-label" value="${escapeAttr(r.label||'')}" maxlength="80" placeholder="${i?'New business bank':'Current bank'}"></label><label>Account name<input class="bank-name" value="${escapeAttr(r.bank_account_name||'')}" maxlength="160"></label><div class="form-grid"><label>Sort code<input class="bank-sort" inputmode="numeric" value="${escapeAttr(r.bank_sort_code||'')}" placeholder="12-34-56"></label><label>Account number<input class="bank-number" inputmode="numeric" value="${escapeAttr(r.bank_account_number||'')}" placeholder="8 digits"></label></div></fieldset>`}).join('')}`;openWorkDialog('Manage two bank accounts','PRIVATE TO YOUR STUDIO',body,async d=>{const accounts=[...d.querySelectorAll('[data-bank-slot]')].filter(x=>x.querySelector('.bank-enabled').checked).map(x=>({id:x.dataset.bankSlot,label:x.querySelector('.bank-label').value.trim(),bank_account_name:x.querySelector('.bank-name').value.trim(),bank_sort_code:x.querySelector('.bank-sort').value.replace(/\s/g,''),bank_account_number:x.querySelector('.bank-number').value.replace(/\s/g,'')}));await api('/api/studio/bank-accounts',{method:'PUT',body:JSON.stringify({accounts})});dashboard=await api('/api/studio/dashboard');render();toast('Bank choices saved. Existing quotes and invoices keep their saved payment details.')},'Save bank accounts')}catch(e){toast(e.message,true)}};
